language: go

go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"

compiler: go

os: 
  - linux
  - osx

arch:
  - amd64
  - arm64

notifications:
  email: false

before_install:
  - cp -r $GOROOT/src/cmd/internal $GOROOT/src/cmd/objfile
  - go get github.com/kr/pretty

script:
  - go build github.com/pkujhd/goloader/examples/loader
  - go tool compile $GOPATH/src/github.com/pkujhd/goloader/examples/base/base.go
  - ./loader -o base.o -run main.main
